import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/compoments/shared/Navbar";
import Footer from "@/compoments/shared/Footer";
import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <Container className="min-h-screen"
        > {children}
        </Container>
        <Footer/>
      </body>
    </html>
  );
}
